Feature/177 memo page
FRONTENDSCHOOL8/Book-Kong pull request #190
Opened 2024-05-12 14:49 UTC by HHeoGeon

## PR 유형
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약
- 메모페이지 구현

### PR 상세
- 메모페이지 구현
- MemoList.jsx <MemoCard> id={memo.id} 추가

### 스크린샷

## 이슈

메모 상세 페이지 마크업 #177

2024-05-13 05:08 UTC, DragonTiger92 requested changes
수정 요청 사항 코멘트 달아놨어. 확인하고 수정할 부분 수정해줘. 그리고 기능 동작 잘 되는지 확인해달라고 요청한 부분 있는데, 그 부분도 확인하고 나서 커밋해줘!

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +        .getOne(memoId, { expand: 'book_id' });
여기도 데이터 잘 불러와지는지 한번 확인해줄래????

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +        <title>책콩 | 기록 페이지</title>
이거 바꾸라니까!!!ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +          {data.updated?.slice(0, 10)}
이거 물음표 데이터 바로 뒤에 붙어야 하는 것 같은데(ex) data?.updated.slice(0,10)), updated가 아니고 data가 객체면 내가 말한 대로 바꿔줘!

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +        <div className=" flex text-xm mt-6 text-[#F24822] font-normal">
여기 아마 주현이가 다 지정해놓은 색깔 변수랑 폰트 디자인 토큰(디자인 변수) 있을 텐데, 이왕 바꿔서 다시 커밋할 거면 이 부분도 바꿔줘!

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +          {data.expand.book_id.title}
옵셔널 체이닝(점 앞에 물음표) 붙일 거면 여기도 붙이는 게 좋을 듯???

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +        <div className=" h-full whitespace-pre-wrap mt-4 text-sm">
여기도 아마 디자인 변수들(색깔, 폰트 등) 있을 텐데, 가급적이면 그거 써줘! 디자인 변수는 style 폴더에 tailwind.css랑 루트 폴더에 있는 tailwind.config.js 확인하면 될 거야.

2024-05-13 05:08 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +          {data.expand.book_id.title}
다른 데에도 data 불러오는 데에 옵셔널 체이닝 붙이면 좋을 것 같아. 기왕 붙일 거면 다 붙여줘!ㅎㅎㅎㅎ

2024-05-19 15:54 UTC, HHeoGeon commented on src/components/organisms/MemoCard/MemoCard.jsx
> +        href={`/record/memo/${id}`}
넵 잘 뜹니다!

2024-05-21 07:01 UTC, DragonTiger92 requested changes
확인 다시 했어ㅎㅎ 추가 요청 사항 하나 적어놨으니까 그거 확인하고, 주현이 PR 머지 되면서 Router.jsx 파일에서 충돌 난 것 같으니까 확인한 다음 해결해서 다시 PR해줘! 그리고 이전에 남겼던 comment들 중에서 하나는 해결 안 돼서 해결 됐다고 표시 안 하고 놔뒀으니까 그것도 해결해서 PR 업데이트 할 때 같이 반영해주고!ㅎㅎㅎ

2024-06-08 06:44 UTC, juhyuny submitted a review, later dismissed
확인-!

2024-06-08 15:03 UTC, juhyuny approved these changes
확인-!

2024-06-08 15:03 UTC, DragonTiger92 approved these changes
확인했어!ㅎㅎㅎㅎㅎㅎㅎ

2024-06-08 15:03 UTC, merged