Feature/19 splashpage
FRONTENDSCHOOL8/Book-Kong pull request #191
Opened 2024-05-13 13:21 UTC by juhyuny

## PR 유형
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [x] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약
SplashPage storybook 파일 생성, SplashPage 컴포넌트 경로 수정

### PR 상세
- SplashPage 폴더 생성 및 storybook 파일 추가
- App.jsx SplashPage 컴포넌트 명 수정

### 스크린샷

## 이슈

2024-05-13 13:58 UTC, DragonTiger92 requested changes
코멘트 남겼어. 확인해줘!ㅎㅎㅎㅎ

2024-05-13 13:58 UTC, DragonTiger92 commented on src/components/pages/SplashPage/SplashPage.stories.js
> +Base.storyName = '';
이것만 컴포넌트 이름 채워서 올려줄래??? 그리고 'DetailBookStateTitle' 컴포넌트도 stories.js에 스토리 이름 없는데 그것도 컴포넌트 이름 넣어서 같이 커밋해주라! 스토리북 켜봤더니 얘네 이름이 안 보여ㅜㅋㅋㅋ

2024-05-13 14:59 UTC, DragonTiger92 commented on src/components/pages/SplashPage/SplashPage.stories.js
> +Base.storyName = '';
수정 요청 사항 반영 된 거 확인 완료

2024-05-13 15:00 UTC, DragonTiger92 approved these changes
확인 다 했어ㅎㅎ 고생 많았어! :)

2024-05-16 06:38 UTC, yen815 approved these changes
확인완! 고생 많았어!

2024-05-17 10:55 UTC, merged