[Feat] 책 등록 페이지에서 책 등록하는 기능 구현
FRONTENDSCHOOL8/Book-Kong pull request #192
Opened 2024-05-19 12:48 UTC by DragonTiger92

## PR 유형

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [x] 주석 추가 및 수정
- [x] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약

- 알라딘 DB에서 특정 책의 데이터를 불러오는 함수 작성

- 책 등록 페이지 내 form 요소들의 data를 수집한 formData 객체를 만들어 북콩 PocketHost DB 내 'library' collection으로 보내는 기능 구현

- 제품 내 추가 수정 요청 사항 작성

- 책 등록 페이지 내 interactive 요소에 micro-animation 적용

  - Framer Motion 모듈 사용

- 제품 내 <a> 태그를 사용하여 페이지 이동을 하던 부분들을 모두 React-router의 <Link> 컴포넌트를 이용하여 React-router를 통해 페이지를 이동하도록 코드 변경

- Molecule 단위 'Link' component 제거 후 해당 컴포넌트 내 JSX 요소들을 React-router의 <Link> 컴포넌트를 이용하여 재작성 및 배치

- Image URL을 인수로 넣으면 File 객체로 변환 시켜주는 유틸 함수 작성

- 성능 최적화를 위해 일부 컴포넌트 memoization 시행

- BackButton 컴포넌트 실행 로직 변경

- 클린 코드를 위해 컴포넌트 정리 및 컴포넌트 구성 코드 변경

- 접근성 향상을 위해 코드 수정

  - WAI-ARIA 기술을 사용하여 마크업 수정

  - TailwindCSS의 'sr-only' 유틸리티 클래스를 사용하여 DOM 요소에 초점이 갈 수 있도록 코드 변경

- StoryBook config 파일 보완

- Bookshelf 조직체 컴포넌트 내에서 데이터가 Bookkong PocketHost 'library' collection으로부터 불러와지지 않을 경우 사용자에게 에러 객체를 throw 하는 코드 작성

- ReadingState 분자 컴포넌트 내 ReadingStateButton 요소들을 button JSX 요소에서 radio input JSX 요소로 변경하여 마크업 구현

- 기타 특이사항 파일 참조

### PR 상세

- 'File changed' 및 'Commits' 영역 참조

### 스크린샷

- 책 등록 기능 구현

![Honeycam 2024-05-19 21-43-56](https://github.com/FRONTENDSCHOOL8/Book-Kong/assets/148827389/e1d10625-2f61-496b-b23e-39381539cac3)

- DB에 등록 된 'library' collection 내 record

![image](https://github.com/FRONTENDSCHOOL8/Book-Kong/assets/148827389/6cd82216-4491-4c45-ae13-a7abdd449cec)

## 이슈

resolves #44

2024-05-24 06:42 UTC, yen815 submitted a review, later dismissed
고생하셨슴다~

2024-08-02 11:16 UTC, HHeoGeon submitted a review, later dismissed
고생하셨습니다..!!

2024-09-28 09:19 UTC, juhyuny requested changes
검토 코멘트 확인 바람-!

2024-09-28 09:19 UTC, juhyuny commented on src/components/molecules/ReadingState/ReadingState.jsx
이 컴포넌트를 div로 말고 fieldset으로 묶고 내부에 '독서상태'라는 legend 태그를 넣으면 어떨까?
폼 요소들을 맥락 그룹으로 묶는 태그야

2024-09-28 09:19 UTC, juhyuny commented on src/components/molecules/TextInputBox/TextInputBox.jsx
얘는 가장 큰 묶음이 li니까 TextInputList 같이 컴포넌트 명을 list를 알 수 있는 이름으로 바꾸는 건 어때?

2024-09-28 09:19 UTC, juhyuny commented on src/components/organisms/BookInfoBox/BookInfoBox.jsx
얘네도 한 화면 내에 input을 묶은 ul이니까 fieldset > legend + ul 로 마크업하는 건 어떨까

2024-09-28 09:19 UTC, juhyuny commented on src/components/pages/RegisterPage.jsx
> +        <div className="bg-[#AAA] w-[1px] h-3"></div>
이거까지,,라는 생각도 있지만 div는 묶음 태그니까 span을 블록요소로 바꿔서 사용하는게 낫지 않을까?

2024-09-28 09:19 UTC, juhyuny commented on src/utils/controlBookData.js
> +    alert('책 사진을 등록해주세요.');
'책 표지를 등록해주세요.'나 '책 이미지를 등록해주세요.'가 좋을 것 같아!

2024-09-28 09:32 UTC, DragonTiger92 commented on src/components/molecules/TextInputBox/TextInputBox.jsx
흠, list면 listitem이 아니라 list (e.g. ul, ol) 로 인식 될 것 같은데, TextInputLi로 바꿀까? 마땅한 이름이 생각 안 나는데, 어때 이건???

2024-09-28 09:35 UTC, juhyuny commented on src/components/molecules/TextInputBox/TextInputBox.jsx
안그래도 묶음으로 보일 것 같다는 생각이었는데 TextInputLi 괜찮은거같아!

2024-09-28 14:00 UTC, DragonTiger92 commented on src/components/molecules/BookFilterBox/BookFilterBox.jsx
변경 완료.

### 변경 사항

- prop 이름 'filterType'을 'readingState'로 변경
- BookFilterButton 컴포넌트가 받는 'type' props를 없애고 children으로 해당 값 입력 받도록 컴포넌트 변경
- Props 이름 변경에 맞춰 'BookFilterBox' 컴포넌트 이름을 'ReadingStateFilter'로 변경
- 'BookFilterBox' 컴포넌트 이름 변경에 맞춰 'BookFilterButton' 컴포넌트 이름을 'StateFilterBtn'으로 변경

### 추가 입력 사항

- 'BookFilterButton' 컴포넌트의 storybook config 파일 입력이 안 되어있어 입력하고 story 추가함.

2024-09-28 14:24 UTC, DragonTiger92 commented on src/components/molecules/ReadingState/ReadingState.jsx
수정 완료.

### 변경 사항

- 컴포넌트 최상단 요소 <div>를 <fieldset>으로 바꿈.
- 바꾼 최상단 <fieldset> 요소 내부에 'A11yHidden' 컴포넌트를 사용하여 legend 요소 입력

2024-09-28 14:34 UTC, DragonTiger92 commented on src/components/molecules/TextInputBox/TextInputBox.jsx
'TextInputBox' 컴포넌트 이름 'TextInputLi'로 수정 완료

2024-09-28 14:44 UTC, DragonTiger92 commented on src/components/organisms/BookInfoBox/BookInfoBox.jsx
수정 완료.

### 변경 사항

- 컴포넌트 최상단 요소 div -> fieldset 변경
- 바꾼 fieldset 요소 하부에 A11yHidden 컴포넌트를 사용하여 legend 요소 추가

2024-09-28 14:49 UTC, DragonTiger92 commented on src/components/pages/RegisterPage.jsx
> +        <div className="bg-[#AAA] w-[1px] h-3"></div>
아니, 난 이런 거 좋아ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이 페이지 컴포넌트는 아예 마크업을 다 뜯어고치고 싶긴 하지만...... 일단 말한 거 수정했어!ㅎㅎㅎㅎ

2024-09-28 14:52 UTC, DragonTiger92 commented on src/utils/controlBookData.js
> +    alert('책 사진을 등록해주세요.');
'책 이미지를 등록해주세요' 문구로 변경 후 commit 완료!

2024-09-28 14:53 UTC, DragonTiger92 reviewed
요청한 변경 사항 전부 변경 완료했어. Conversation들에 있는 comment들 확인하고 다시 리뷰해줘! @juhyuny

2024-09-28 17:34 UTC, juhyuny approved these changes
확인~! 고생했어!! 👍

2024-09-29 08:45 UTC, merged