Feature/101 feed registration
FRONTENDSCHOOL8/Book-Kong pull request #194
Opened 2024-05-22 17:06 UTC by HHeoGeon

## PR 유형
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약
- 피드 작성 후 데이터 저장

### PR 상세
- 피드 페이지에서 아이콘 클릭 시 피드 페이지로 이동
- 어떤 책의 피드를 작성할 것인지 유저가 저장한 책 리스트 바탕으로 지정 가능
- 저장 후 피드 페이지로 이동
- 데이터에 저장된 피드구현
-  react-query-devtools 설치
- pull 후 npm i 필요!
- #117 메모 상세 페이지 merge 전이라 파일x

### 스크린샷

## 이슈

resolves #101
resolves #102

2024-05-24 07:04 UTC, yen815 submitted a review, later dismissed
고생했어~ 확인완

2024-05-24 07:34 UTC, DragonTiger92 requested changes
건아 PR 확인했어. 수정 요청 사항 올려놨으니까 comment 달고 수정해서 업데이트해줘!

2024-05-27 16:15 UTC, HHeoGeon commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +      const formData = Object.fromEntries(
폼데이터 객체복사가 안되고 덮어쓰기가 돼서 안돼요

2024-05-27 16:32 UTC, HHeoGeon commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +          id="bookInfo"
세이브 버튼을 폼에 연결하는데 세이브 버튼 컴포넌트에 아이디가 북 인포로 명시되어 있고 추가적으로 아이디를 넣어줄 수 있는 상황이 아니라 헤더에 있는 세이브 버튼의 로직이 변경되지 않는 이상 지금은 못 바꿔요ㅠ

2024-05-28 15:44 UTC, DragonTiger92 commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +      const formData = Object.fromEntries(
폼데이터 객체 복사가 안 되면 안 되는 거야...??????

2024-05-28 16:24 UTC, DragonTiger92 requested changes
건아, 꼭 수정해야 할 것 같은 것들만 코멘트 달아놨으니까 보고 수정해줘.....;;;;;;......

2024-05-28 16:24 UTC, DragonTiger92 commented on src/components/atoms/LargeHeaderIcon/LargeHeaderIcon.jsx
> +      src: '/images/icons/newrecord.svg',
위에 path 값 수정 되면 여기 href 값도 수정해줘.

2024-05-28 16:24 UTC, DragonTiger92 commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +          id="bookInfo"
아, 그래서 그런 거구나....... 그거 내가 SaveButton 안그래도 로직 변경해놨는데, 어차피 로직 변경 된 거 develop에 머지할 거면 이것도 바꿔야하니까 미리 바꿔놓자. 그냥 이 페이지 마크업 저기 `<Header title="피드 작성" />` 이라고 써 놓은 컴포넌트 사용 코드에다가 formId="feed-data" prop 추가해주기만 하면 돼.
 이거 어차피 책 등록 페이지에도 저장 버튼 들어가는데 나는 그거 마크업 할 때 거기에 있는 form 요소에 id 값 bookInfo랑 다른 거 줘서, SaveButton 들어가는 모든 페이지에 있는 form 요소 id "bookInfo"로 맞출 거 아니면 수정하긴 해야 하거든. 그냥 내 거 브랜치 PR 할 때 너가 바꿔준 부분 반영해서 기능 잘 작동하는지 테스트 해보고 PR할게, 일단 여기 id는 "feed-data"로 바꿔서 PR 해줘.

### 정리

- 본 페이지 form 태그 내 id 값 "feed-data"로 바꾸기.

- 본 페이지 내에서 사용한 Header 컴포넌트 마크업 코드에 prop으로 formId="feed-data" 추가하기.

2024-05-28 16:24 UTC, DragonTiger92 commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +          <input
건아, 위에 거 수정 때문에 어차피 PR 한번 더 업데이트 해줘야 하는데, 이거 label 하나 쓰는 거 어려운 거 아니니까 label은 업데이트 할 때 하나 넣어줘......;;;;;;

2024-05-30 06:12 UTC, DragonTiger92 approved these changes
@HHeoGeon 수고했어. FeedRegisterPage 컴포넌트 안에 있는 form 태그 id 관련해서 내가 거기에 코멘트 하나 달아놨으니까 merge 하기 전에 한번 확인해줘! :)

2024-05-30 06:12 UTC, DragonTiger92 commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +          id="bookInfo"
건아, 이거 id 그럼 내가 너 거 최신화하고 나서 내 거 머지하기 전에 수정해놓는다??? @HHeoGeon

2024-05-30 08:21 UTC, yen815 submitted a review, later dismissed
고생 많았어~

2024-06-02 04:25 UTC, DragonTiger92 requested changes
건아, 마지막 수정 사항일 것 같아. 코멘트 달았으니까 확인하고 마지막으로 업데이트 해줘!

2024-06-02 04:25 UTC, DragonTiger92 commented on src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
> +      <Header title="피드 작성" />
건아, 여기다가도 'formId="feed-data"' prop 추가해줘야 해. [https://github.com/FRONTENDSCHOOL8/Book-Kong/pull/194#discussion_r1617580826](url) 여기에다가도 적어놨는데 못 봤나보네;;;;;; 이것만 수정하면 이 PR은 더 수정할 거 없을 것 같아. 이것만 수정해주고, 내가 열어놓은 conversation들은 이거 너가 업데이트하면서 확인하고 해결 됐을테니까 한번 더 확인 되면 다 닫아줘. 그리고 알려주면 승인해놓을게!

2024-06-04 14:38 UTC, DragonTiger92 submitted a review, later dismissed
수고 많았어! 고생했다!ㅎㅎㅎㅎㅎㅎ 잘해줘서 고마워~!!!! :)

2024-06-08 06:42 UTC, juhyuny submitted a review, later dismissed
고생해써-!🍀

2024-06-08 14:44 UTC, DragonTiger92 approved these changes
확인했어!ㅎㅎㅎㅎㅎ

2024-06-08 14:53 UTC, juhyuny approved these changes
확인-!

2024-06-08 14:53 UTC, merged