Feature/179 feed detail markup
FRONTENDSCHOOL8/Book-Kong pull request #195
Opened 2024-06-04 10:55 UTC by yen815

## PR 유형
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약
feed detail markup

### PR 상세
feed detail markup

### 스크린샷
![image](https://github.com/FRONTENDSCHOOL8/Book-Kong/assets/119932452/d002fa4f-1344-4327-94fc-b5280e55a757)

## 이슈

resolves #179 
resolves #27

2024-06-04 14:27 UTC, DragonTiger92 requested changes
예은아, 신경 써서 마크업 잘 해줘서 고마워ㅎㅎㅎㅎㅎㅎ 수정 사항 comment들로 남겼는데, 자잘한 것들이라 금방 수정할 수 있을 거야. 보고 수정해서 PR 업데이트한 다음에 카톡에서 알려줘!

2024-06-04 14:27 UTC, DragonTiger92 commented on src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.jsx
> +          alt="/"
바꾸는 김에 이거 alt 값도 "캐릭터"로 바꿔줘. 얘는 의미가 있는 이미지라서 alt 값 넣어주는 게 나을 것 같아. 그리고 alt 값이 없을 때에는 "/"보다 빈 문자열 넣어주는 게 더 나을 것 같아. 참고해줘!ㅎㅎㅎㅎ

2024-06-04 14:27 UTC, DragonTiger92 commented on src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.jsx
> +          alt="/"
아래 있는 댓글 박스들에 있는 캐릭터 이미지들에도 alt 값 다 수정 부탁해!

2024-06-04 14:27 UTC, DragonTiger92 commented on src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.jsx
> +import {} from 'prop-types';
얘랑 아래 있는 84번 줄 의미 없는 코드는 삭제해주라!ㅎㅎㅎㅎㅎㅎ

2024-06-04 14:27 UTC, DragonTiger92 commented on src/components/molecules/FeedDetailPostContents/FeedDetailPostContents.jsx
> +import {} from 'prop-types';
얘도 위에랑 같이 의미 없는 코드(1번, 18번 줄)는 삭제해서 커밋해줘!ㅎㅎㅎㅎㅎㅎ

2024-06-04 14:27 UTC, DragonTiger92 commented on src/components/molecules/FeedDetailPostContents/FeedDetailPostContents.jsx
> +import {} from 'prop-types';
그리고 다른 파일들에도 이런 것들 같이 삭제해서 커밋 부탁해!ㅎㅎㅎ

2024-06-04 14:27 UTC, DragonTiger92 commented on src/styles/tailwind.css
> +.bg-gray {
이거는 이미 tailwind.config.css에 디자인 변수 값 있어서 굳이 코드 추가 안 해도 될 것 같은데, 이 코드 지우고 위에 'bg-gray' className 쓴 main 영역은 "bg-background-gray"로 바꾼 다음에 잘 나오는지 테스트 한번 해서 다시 커밋해줄래???

2024-06-05 08:12 UTC, juhyuny commented on src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.jsx
> +          <img src="/images/icons/arrow-up.svg" alt="검색버튼" />
내가 input placeholder 값을 안바꿨네 ㅜㅜ 미안해ㅜㅜ 
**placeholder="댓글을 남겨보세요!"** 로 수정 부탁해 !!

2024-06-05 08:13 UTC, juhyuny commented on public/images/icons/newrecord-black.svg
이것도 아이콘 컬러가 시안에 누락되어있어서 얼마전에 ㅜㅜ 다시 바꿨었어!! 주황색으로 부탁드림다🥹

2024-06-07 08:06 UTC, DragonTiger92 approved these changes
확인했어. 수고 많았어! :)

2024-06-08 04:55 UTC, juhyuny approved these changes
고생하셔씁니다🍀

2024-06-08 12:19 UTC, merged