[Feat] BookDetailPage 데이터 가져오는 기능 구현 외
FRONTENDSCHOOL8/Book-Kong pull request #196
Opened 2024-06-15 09:40 UTC by juhyuny

## PR 유형
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약
BookDetailPage 마크업 및 데이터 가져오는 기능 구현 외

### PR 상세
BookDetailPage 
- 마크업 및 스타일링
- router.jsx에 로더함수로 페이지에 데이터 가져오는 기능 구현
- DetailBookMemo, DetailBookFeed 리스트가 없는 예외상황 컴포넌트 NoneCardState 추가 외

MemoDetailPage
- 레이아웃 스타일 수정
- router.jsx에 로더함수로 페이지에 데이터 가져오는 방식 변경

### 스크린샷
<img width="442" alt="스크린샷 2024-06-15 오후 6 15 22" src="https://github.com/FRONTENDSCHOOL8/Book-Kong/assets/141771716/aef0298b-2316-45b6-bdc5-ff7981103fea">
<img width="446" alt="스크린샷 2024-06-15 오후 6 16 04" src="https://github.com/FRONTENDSCHOOL8/Book-Kong/assets/141771716/ed166b94-f48b-457a-b1a4-ac3ae18ffc08">

## 이슈
resolves #70

2024-06-17 07:55 UTC, DragonTiger92 requested changes
Comment들 남겼으니까 확인하고 수정할 부분은 수정해줘. 고생 많았어!!! :)

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
>      setListCount(data?.length || 0);
이 함수 실행부 안에 argument로 들어간 식은 data의 length 값이 falsy하지 않으면 data의 length 값을 반환하는 거지????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
> +          <a
얘도 React router에 있는 Link component로 바꿔서 구현해줘!

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
> +              <p></p>
얘는 빈 문자열 말고 `p` 태그를 넣어줘야 하는 건가???????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
> +  }),
얘도 바꾸는 김에 isRequired 넣어줘, data 자체에!

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStatePeriod/DetailBookStatePeriod.jsx
> +        <div className="hidden">
얘는 아예 book status가 '희망 도서'면 나올 필요가 없는 애인 것 같은데..... hidden 클래스를 줘서 숨겨야 하는 거야, 아예 렌더링을 안 시키는 게 아니라????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStatePeriod/DetailBookStatePeriod.jsx
> +    start_date: string,
여기도 보니까 start_date 말고 end_date도 있어야 하고 이거 둘 다 필수 값인 것 같은데 type 명시 그렇게 해주면 될 것 같고.... state 자체도 필수 값인 것 같으니까 필수 값으로 type 명시해줘!ㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStateProgress/DetailBookStateProgress.jsx
> +        <div className="hidden">
얘도 위에랑 똑같은 질문! hidden 클래스를 줘서 숨겨야 하는 요소인 거야, 렌더링을 아예 안 시키는 게 아니라???

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStateProgress/DetailBookStateProgress.jsx
> +  state: shape({
같은 파일에 있는 코드들 바꾸는 김에 이 state도 isRequired 처리해주면 좋을 것 같아!ㅎㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStateRate/DetailBookStateRate.jsx
> +function DetailBookStateRate({ state: bookData }) {
근데 궁금한 게 있는데, 컴포넌트들이 props로 받는 bookData 관련 자료들 보면 bookData가 있고 bookState가 있던데, 둘이 뭐가 다른 거야???

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStateRate/DetailBookStateRate.jsx
> +    score: number.isRequired,
이거 score 숫자 자료형으로 들어오는 거 맞지??? 코드를 안 봐서 모르겠는데, 혹시 서버에서 가져오는 자료 그대로면 숫자로 들어와도 string 형으로 들어오는 건 아닌가 해서ㅋㅋㅋㅋㅋㅋ 확인 한번 해봐줄래???

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStateRate/DetailBookStateRate.jsx
> +    score: number.isRequired,
그리고 하는 김에 state props 자체도 필수 값으로 타입 지정 부탁해!ㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/DetailBookStateRateContent/DetailBookStateRateContent.jsx
> +    score: number,
얘도 score 타입 확인해주고 필수 값들로 score랑 state 지정 부탁해!ㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/NoneCardState/NoneCardState.jsx
> +      <img src="/images/characters/잠금캐릭.png" alt="" width="82" />
얘도 이미지 너비는 고정으로 가는 거지????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/NoneCardState/NoneCardState.stories.js
얘는 story 만들어주면 좋을 것 같아! 어차피 StoryBook 쓴다고 얘기하려면 story 정도는 만들 줄 알아야하니까, 이 컴포넌트 대상으로 data="memo"일 때랑 data="feed"일 때 story 한번 만들어볼래???ㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/NoneCardState/NoneCardState.jsx
> +function NoneCardState({ data }) {
이거 코드 대충 봤더니 NoneCardState에 들어오는 `data` props는 그냥 컴포넌트 사용할 때 임의로 'memo'나 'feed' 값 넣어주는 것 같던데... 그럼 그냥 영어로 넣지 말고 아예 한글로 넣어주면 안 돼?? 그럼 아래 5번 줄이랑 7번 줄 같은 데서 상태 선언하고 set 함수로 바꿔주는 작업이 필요 없을 것 같은데...???????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/OrderButton/OrderButton.jsx
> +  const className = `${defaultClassName} ${customClassName}`;
이거는 그냥 참고로 보고 resolve 됐다고 닫아줘. 이거 이렇게 합성하니까 style이 제대로 작동 안 하는 부분이 있어서 내가 이거 보정할 수 있는 유틸 함수 만들어놨거든??? 그러니까 나중에 너 저장소로 fork 떠가서 작업할 때 그 함수 써서 defaultClassName이랑 customClassName 합성해봐.
 이게 tailwindCSS에서 defaultClassName이랑 customClassName 합성할 때 종종 나타나는 문제라서 이거 해결할 수 있는 NPM도 있다고 알고 있어. 한 두 가지 이미 만들어진 해결 방안이 있다고 하니까 그냥 알아두면 이것도 좋을 것 같아!ㅎㅎㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/OrderButton/OrderButton.jsx
> +  const className = `${defaultClassName} ${customClassName}`;
지금 여기서는 이 합성 방식 문제 없이 잘 적용 되는 거지???

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/molecules/OrderButton/OrderButton.jsx
> +function OrderButton({ onClick, order, customClassName }) {
이 customClassName 같은 경우에는 이렇게 props 이름을 만들면 쓰는 사람이 이 컴포넌트 쓸 때 `<OrderButton customClassName="~~~">` 이렇게 써야 하잖아??? 그러면 불편하고 이질감 드니까 나 같은 경우에는 className으로 props 사용할 수 있게 만들어놓고 컴포넌트 안에서 그 `className` props 이름을 customClassName으로 바꿔놓거든.
 그렇게 바꿔놓으면 내 생각에 사용성이 더 좋아질 것 같아. 참고해서 바꾸고 싶으면 바꿔서 commit 해줘!

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/organisms/DetailBook/DetailBook.jsx
> +DetailBook.propTypes = {};
이 코드는 안 쓰니까 그냥 지워줘!ㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +  console.log(memoId);
console.log 코드는 삭제해줘!ㅎㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +  const memoId = useLoaderData();
이거 변수에 들어가는 게 memoId가 아니라 그 memoId를 가진 데이터니까 변수 이름을 그냥 `memo`로 해줄 수 있어???ㅎㅎㅎ

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +        <article className="px-4 py-6 border-y bg-grayscale-white border-1 border-grayscale-200 full-height">
section 없이 바로 article인데, 표준에 어긋나는 것 같지는 않지만.... section이 아니라 article이 더 나은 거야????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +            {memoId?.expand?.book_id?.title}
이거 optional chaining 이렇게 많이 달아둘 필요 없을 것 같은데...... optional chaining도 있으면 다 연산될 거라 메모리 잡아먹을 것 같거든...;; 여기 코드에 optional chaining 필요할 것 같은 부분만 chaining 걸어줄 수 있어????

2024-06-17 07:55 UTC, DragonTiger92 commented on src/utils/controlBookData.js
> +export async function getLibraryData(recordId) {
이것도 그냥 참고로 보고 대화 닫아줘. `Data`라는 단어의 추상성이 너무 커서 사실 조금 더 적합한 단어가 있으면 더 적합한 단어를 쓰는 게 코드 보고 프로젝트 추상화 하는 게 좋다고 생각하거든??? 이 함수는 'library' collection의 record를 가져오는 함수니까 getLibraryRecord라고 쓰면 처음 보는 사람이 코드 보고 이 함수가 무슨 함수를 하는지 이해하기가 훨씬 편할 거야. 참고로만 봐줘!ㅎㅎㅎㅎㅎㅎ

2024-06-17 08:06 UTC, juhyuny commented on src/components/atoms/DetailBookImage/DetailBookImage.jsx
> +      width={206}
응 사이즈 고정-!

2024-06-17 08:11 UTC, juhyuny commented on src/components/atoms/DetailBookName/DetailBookName.jsx
완 ✅

2024-06-17 08:13 UTC, juhyuny commented on src/components/atoms/DetailBookStatePeriodContent/DetailBookStatePeriodContent.jsx
> +    start_date: string.isRequired,
근데 case가 둘중 하나씩만 해당이 되는데 둘다 isRequired 해놔도 괜찮아?

2024-06-17 08:34 UTC, juhyuny commented on src/components/atoms/DetailBookStatePeriodContent/DetailBookStatePeriodContent.jsx
> +    start_date: string.isRequired,
완 ✅

2024-06-17 08:40 UTC, juhyuny commented on src/components/atoms/DetailBookStateProgressContent/DetailBookStateProgressContent.jsx
> +          {daysBetweenDates} 일
완 ✅

2024-06-17 08:40 UTC, juhyuny commented on src/components/molecules/BookDetailNavigation/BookDeatilNavigation.stories.js
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ제성제성!

2024-06-17 08:45 UTC, juhyuny commented on src/components/atoms/DetailBookStateProgressContent/DetailBookStateProgressContent.jsx
> +    end_date: string.isRequired,
완 ✅

2024-06-17 08:45 UTC, juhyuny commented on src/components/molecules/BookDetailNavigation/BookDetailNavigation.jsx
> +  const [activeTab, setActiveTab] = useState('bookInfo');
확인 ✅

2024-06-17 08:52 UTC, juhyuny commented on src/components/molecules/DetailBookFeed/DetailBookFeed.jsx
> +          <a href="/feed" className="text-grayscale-500 contents-sm-bold">
완 ✅

2024-06-17 08:52 UTC, juhyuny commented on src/components/molecules/DetailBookFeed/DetailBookFeed.jsx
> +  data: shape({
완 ✅

2024-06-17 08:57 UTC, juhyuny commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
> +          <a
완 ✅

2024-06-17 08:58 UTC, juhyuny commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
> +  }),
완 ✅

2024-06-17 09:05 UTC, juhyuny commented on src/components/molecules/DetailBookStateProgress/DetailBookStateProgress.jsx
> +  state: shape({
완 ✅

2024-06-17 09:05 UTC, juhyuny commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +        <article className="px-4 py-6 border-y bg-grayscale-white border-1 border-grayscale-200 full-height">
상의완료 ✅

2024-06-17 09:07 UTC, juhyuny commented on src/components/molecules/DetailBookStateRate/DetailBookStateRate.jsx
> +function DetailBookStateRate({ state: bookData }) {
ㅋㅋㅋㅋㅋㅋㅋ욘범이 저번에 data값 인건 data, state값 인건 state로 넣는게 명시적일것 같다고 해서 하긴했는데,,

2024-06-17 10:47 UTC, juhyuny commented on src/components/molecules/DetailBookStatePeriod/DetailBookStatePeriod.jsx
> +        <div className="hidden">
hidden이 display: none이라서 데이터 받을 필요없는 애들은 요소자체가 사라지긴해!

2024-06-17 10:48 UTC, juhyuny commented on src/components/molecules/DetailBookStateProgress/DetailBookStateProgress.jsx
> +        <div className="hidden">
얘도 위에랑 똑같은 답변~! 생각말해줘

2024-06-17 10:53 UTC, juhyuny commented on src/components/molecules/DetailBookStateRate/DetailBookStateRate.jsx
> +    score: number.isRequired,
완 ✅

2024-06-17 11:04 UTC, juhyuny commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
> +              <p></p>
얘는 레이아웃때문에 저렇게 줬던건데 
그냥 빈문자로 바꾸고 flex배치 주는 div한테 
리스트 유무에 따라 바뀌는 스타일 조건 걸어줬어!! 

수정완✅

2024-06-17 11:10 UTC, juhyuny commented on src/components/molecules/DetailBookInfoDate/DetailBookInfoDate.jsx
> +    description: string.isRequired,
완 ✅

2024-06-17 11:11 UTC, juhyuny commented on src/components/molecules/DetailBookInfoDate/DetailBookInfoDate.jsx
> +  const pulicationDate = calculatePublicationDate(bookData.publication_date);
없애버렷슴니다
완 ✅

2024-06-17 11:13 UTC, juhyuny commented on src/components/molecules/DetailBookInfoPage/DetailBookInfoPage.jsx
> +    description: string.isRequired,
완 ✅

2024-06-17 11:14 UTC, juhyuny commented on src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
>      setListCount(data?.length || 0);
응응

2024-06-17 11:18 UTC, juhyuny commented on src/components/molecules/NoneCardState/NoneCardState.jsx
> +      <img src="/images/characters/잠금캐릭.png" alt="" width="82" />
응응 고정이야!

2024-06-17 11:21 UTC, juhyuny commented on src/components/molecules/NoneCardState/NoneCardState.jsx
> +function NoneCardState({ data }) {
맞아!!!!
완 ✅

2024-06-17 11:22 UTC, juhyuny commented on src/components/molecules/OrderButton/OrderButton.jsx
> +  const className = `${defaultClassName} ${customClassName}`;
> 지금 여기서는 이 합성 방식 문제 없이 잘 적용 되는 거지???

응!!

2024-06-17 11:23 UTC, juhyuny commented on src/components/molecules/OrderButton/OrderButton.jsx
> +function OrderButton({ onClick, order, customClassName }) {
확인 완✅

2024-06-17 11:24 UTC, juhyuny commented on src/components/organisms/DetailBook/DetailBook.jsx
> +DetailBook.propTypes = {};
완 ✅

2024-06-17 11:26 UTC, juhyuny commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +  console.log(memoId);
완 ✅

2024-06-17 11:26 UTC, juhyuny commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +            {memoId?.expand?.book_id?.title}
완 ✅

2024-06-17 11:27 UTC, juhyuny commented on src/utils/controlBookData.js
> +export async function getLibraryData(recordId) {
확인 완✅

2024-06-17 11:28 UTC, juhyuny commented on src/components/pages/MemoDetailPage/MemoDetailPage.jsx
> +  const memoId = useLoaderData();
완✅

2024-06-17 11:34 UTC, juhyuny commented on src/components/molecules/DetailBookStateRateContent/DetailBookStateRateContent.jsx
> +    score: number,
완 ✅

2024-06-17 11:44 UTC, juhyuny commented on src/components/atoms/RegistrationIcon/RegistrationIcon.jsx
> +    <Link to={`/${page}/registration`}>
완 ✅

2024-06-17 12:24 UTC, juhyuny commented on src/components/molecules/DetailBookStatePeriod/DetailBookStatePeriod.jsx
> +        <div className="hidden">
완 ✅

2024-06-17 12:42 UTC, juhyuny commented on src/components/molecules/DetailBookStateProgress/DetailBookStateProgress.jsx
> +        <div className="hidden">
완 ✅

2024-06-17 12:43 UTC, juhyuny commented on src/components/molecules/DetailBookStateRate/DetailBookStateRate.jsx
> +function DetailBookStateRate({ state: bookData }) {
확인 완 ✅

2024-06-21 13:11 UTC, DragonTiger92 commented on src/components/molecules/NoneCardState/NoneCardState.stories.js
추후 진행하기로 협의함.

2024-06-21 13:24 UTC, DragonTiger92 approved these changes
고생 많았어! 😄👍

2024-06-24 03:57 UTC, yen815 approved these changes
고생많았어!!

2024-06-24 08:11 UTC, merged