[Refactor] User의 book_height와 level을 DB 내 'users' collection에서 가져와서 렌더링하는 기능 개발 외
FRONTENDSCHOOL8/Book-Kong pull request #202
Opened 2024-10-14 09:59 UTC by DragonTiger92

## PR 유형
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [x] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

## PR 체크리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 내용 요약

- 캐릭터 페이지, 마이페이지 내 유저의 book_height, level 정보를 DB 내 'library' collection에서 가져온 자료를 바탕으로 컴포넌트 내에서 계산하는 대신 'users' collection에서 바로 가져와 렌더링하도록 코드 변경
- 캐릭터 페이지, 마이페이지에서 사용하는 'users' collection의 정보를 Router.jsx에서 'loader' props를 이용하여 공급
- BookTree 컴포넌트, '기록 페이지 - 메모' 컴포넌트, 피드 페이지 내 FeedCard 컴포넌트에 들어가는 자료 loading 중 skeleton UI를 보여주는 코드 추가
- MypagePage.jsx 내 마크업 구조 수정, 페이지 내 캐릭터 렌더링 영역 및 '테마 설정' 영역의 style 수정
- 피드 페이지 내 FeedCard 클릭 시 피드 상세 페이지로 이동하는 기능 추가
- 캐릭터 페이지 내 캐릭터 목록에서 각 캐릭터 카드 클릭 시 위 캐릭터 정보 렌더링 영역에 클릭한 캐릭터의 정보가 렌더링 되도록 기능 개발
- 사용하지 않는 유틸 함수들 및 React hook 파일들 제거

### PR 상세

- 책 등록 시 PocketBase DB 내 'users' collection에 해당 내용들 update 되도록 만드는 유틸 함수 controlBookData.js에 생성
- MypagePage 내 마크업 semantic하게 변경 및 A11yHidden 컴포넌트를 이용하여 각 섹션 요소 하부에 heading들 추가
- 캐릭터 페이지의 캐릭터 목록 내 캐릭터 카드 클릭 시 캐릭터 정보 렌더링 영역에 클릭한 자료가 띄워질 수 있도록 CharacterCollection.jsx에 React 상태 추가
- FeedCard와 LoginPage 내 '회원가입' 텍스트에 React Router의 Link 컴포넌트를 이용해 link routing 기능 추가
- 기타 변경사항들 Commits 및 Files changed 영역 참고

### 스크린샷

- BookTree 컴포넌트 내 자료 loading 시 skeleton UI 적용

  ![Honeycam 2024-10-14 18-18-07](https://github.com/user-attachments/assets/d026ead3-6010-4955-9bcf-6dadef2090a6)

- '기록 페이지 - 메모' 컴포넌트 내 자료 loading 시 skeleton UI 적용

  ![Honeycam 2024-10-14 18-19-48](https://github.com/user-attachments/assets/d62eb9c9-a151-47b0-b76f-2fd843c1bc7a)

- 피드 페이지 내 자료 loading 시 skeleton UI 적용

  ![Honeycam 2024-10-14 18-20-59](https://github.com/user-attachments/assets/caaeb442-9874-4376-b483-6dcafb114495)

- 캐릭터 페이지 내 자료를 React Router의 'loader' props를 이용하여 공급

  ![Honeycam 2024-10-14 18-22-30](https://github.com/user-attachments/assets/8f2b5059-868d-48ab-a178-4cd0617a600a)

- 마이페이지 내 유저 자료 'loader' props로 공급 및 캐릭터 렌더링 영역, 테마 설정 영역 style 수정

  ![Honeycam 2024-10-14 18-25-09](https://github.com/user-attachments/assets/7b7fff3e-1227-4fe6-a4fc-05b0b9faa9c0)

- 피드 페이지 내 FeedCard 클릭 시 피드 상세 페이지로 이동하는 기능

  ![Honeycam 2024-10-14 18-27-29](https://github.com/user-attachments/assets/9f25296f-5988-4a1e-8f9b-9bc405668865)

- 캐릭터 페이지 내 캐릭터 목록의 개별 카드 클릭 시 클릭한 캐릭터의 정보가 UserCharacterCard 영역에 렌더링 되는 기능

  ![Honeycam 2024-10-14 18-28-44](https://github.com/user-attachments/assets/db64377b-4282-472d-94c7-71ae346bc930)

## 이슈

2024-10-20 06:22 UTC, juhyuny reviewed
검토 완!

2024-10-20 06:22 UTC, juhyuny commented on src/components/organisms/FeedList/FeedList.jsx
> +            </Skeleton>
1. 이건 스켈레톤이 잠시 나오는거라 영향이 있을까 싶긴 한데 ul바로 아래 skeleton요소가 들어가 있는게 부적합한거 같아
ul 직속자식은 li만 와야하는걸로 알고 있어서! 

2. 아예 ul을 section혹은 article로 바꾸고, feedcard 컴포넌트도 li가 아닌 article로 바꾸는게 어떨까?

2024-11-03 01:21 UTC, DragonTiger92 commented on src/components/atoms/CharacterImg/CharacterImg.jsx
> +  return <img src={userCharacterImg} alt="캐릭터 이미지" width={150} />;
이름은 사용자가 다 외우고 있지 않을 것 같은데, `${characterData.level} 단계`로 alt 값을 넣어주는 건 어때???

2024-11-03 03:42 UTC, juhyuny commented on src/components/atoms/CharacterImg/CharacterImg.jsx
> +  return <img src={userCharacterImg} alt="캐릭터 이미지" width={150} />;
캐릭터 단계랑 이름을 같이 넣어주는건??

2024-11-03 03:46 UTC, DragonTiger92 commented on src/components/atoms/CharacterImg/CharacterImg.jsx
> +  return <img src={userCharacterImg} alt="캐릭터 이미지" width={150} />;
호오... 그렇게 해볼게!

2024-11-03 04:06 UTC, DragonTiger92 commented on src/components/atoms/CharacterImg/CharacterImg.jsx
> +  return <img src={userCharacterImg} alt="캐릭터 이미지" width={150} />;
@juhyuny 이거 시안 보니까 어차피 캐릭터 이미지가 들어가는 모든 곳에 캐릭터 이름이 표현 돼있는 요소가 따로 있어서 굳이 캐릭터 이름까지 alt 값에 넣을 필요는 없을 것 같은데, 어떻게 생각해??? 일단 alt 값에는 `${charLevel}단계 캐릭터`라고만 넣고, 나중에 마크업을 캐릭터 이름이랑 이미지랑 연결시키는 방식으로 가도 괜찮을 것 같은데... 예를 들면 aria-labelledby로 둘을 연결시켜준다던가...???

2024-11-06 12:41 UTC, DragonTiger92 commented on src/components/organisms/FeedList/FeedList.jsx
> +            </Skeleton>
1. ul 아래 li를 넣고 li 안에 Skeleton 컴포넌트를 넣은 후 Skeleton 컴포넌트 안에 box 크기로 styling 되어 있는 div 요소를 넣어 문제 해결.
2. FeedList가 list item이라고 할 수 있는 FeedCard의 부모 요소로, ul 요소로 마크업 돼야 하는 게 맞는 것 같아. 1번 문제를 해결해서 ul 아래 li가 나오도록 마크업 수정했어!

2024-11-06 13:46 UTC, DragonTiger92 commented on src/components/organisms/CharacterCollection/CharacterCollection.jsx
>        <div className="flex justify-between pt-[76px] pb-[120px] w-full flex-col gap-4">
1. div 제거하고 main 요소 안에 UserCharacterCard와 CharacterList 컴포넌트를 바로 넣음.
2. 기존 div 내 'flex' utility className과 padding bottom 관련 utility className 삭제
3. 아래 간격 margin으로 띄움.

2024-11-06 14:10 UTC, DragonTiger92 commented on src/components/atoms/CharacterImg/CharacterImg.jsx
> +  return <img src={userCharacterImg} alt="캐릭터 이미지" width={150} />;
@juhyuny 과의 협의로 alt 값 변경 : "캐릭터 이미지" -> `${charLevel}단계 캐릭터 ${charName}`으로 변경

2024-11-06 14:11 UTC, juhyuny requested changes
고생했음다~!

2024-11-06 14:11 UTC, juhyuny commented on src/components/atoms/CharacterImg/CharacterImg.jsx
> +  return <img src={userCharacterImg} alt="캐릭터 이미지" width={150} />;
확인 완료✅

2024-11-06 14:13 UTC, juhyuny approved these changes

2024-11-06 14:13 UTC, merged